### ISSUE TITLE
大佬们，这个可以通过方糖公众号推吗

### ISSUE THREAD

**Issue by 50801684** [easychen/nCoV-push#3]

**Comment by sy-records** [comment]
看readme，配置好key就是方糖server酱推送

**Comment by 50801684** [comment]
> 看readme，配置好键就是方糖服务器酱汁

把'填写SendKey'换成我的sckey就可以通过方糖推送了吗

**Comment by sy-records** [comment]
是的



---原始邮件---
发件人: "50801684"<notifications@github.com&gt;
发送时间: 2020年1月24日(周五) 上午10:45
收件人: "easychen/nCoV-push"<nCoV-push@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;;
主题: Re: [easychen/nCoV-push] 大佬们，这个可以通过方糖公众号推吗 (#3)


 
看readme，配置好键就是方糖服务器酱汁
  
把'填写SendKey'换成我的sckey就可以通过方糖推送了吗

**Comment by 50801684** [comment]
> 是的
> […](#)
> ---原始邮件--- 发件人: "50801684"<notifications@github.com&gt; 发送时间: 2020年1月24日(周五) 上午10:45 收件人: "easychen/nCoV-push"<nCoV-push@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;; 主题: Re: [easychen/nCoV-push] 大佬们，这个可以通过方糖公众号推吗 (#3) 看readme，配置好键就是方糖服务器酱汁 把'填写SendKey'换成我的sckey就可以通过方糖推送了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢大佬了
