### ISSUE TITLE
如何通过自有公众号推？必须通过方糖吗？

### ISSUE THREAD

**Issue by Gejiafeng** [easychen/nCoV-push#4]
如何通过自有公众号推？必须通过方糖吗？

**Comment by Gejiafeng** [comment]
自己学校公众号粉丝有几万，这样通过自有公众号方便学生查询

**Comment by easychen** [comment]
> 如何通过自有公众号推？必须通过方糖吗？

推送到其他平台把42行推送代码换掉就行。

公众号如何推送需要自己查文档写，不光是代码，还要申请模板消息。查询部分也是，需要自己实现查询。
